import type { Metadata } from 'next'
import Header from '@/components/shared/header'
import '@/globals.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<>
			<Header />
			<main className='p-10'>{children}</main>

			<footer></footer>
		</>
	)
}
