import type { Metadata } from 'next'
import Header from '@/components/shared/header'
import '@/globals.css'
import Container from '@/components/shared/container'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function UserLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<div className='flex flex-col overflow-y-hidden'>
			<Container>
				<Header />
				<main className='px-10 w-full h-full'>{children}</main>
			</Container>
		</div>
	)
}
