import { UsersList } from '@/components'
import { UsersListSkeletons } from '@/components/ui/skeletons'
import { Metadata } from 'next'
import { Suspense } from 'react'

export const metadata: Metadata = {
	title: 'Users | Next.js Training',
	description: 'Generated by create next app',
}

export default function Users() {
	return (
		<div className='relative w-full h-[600px] overflow-y-auto px-3'>
			<Suspense fallback={<UsersListSkeletons />}>
				<UsersList />
			</Suspense>
		</div>
	)
}
