import { ProfileHeader } from '@/components/shared/profile/profile-header'
import { PostsList } from '@/components/shared/posts/posts-list'
import { PostListSkeletons, ProfileHeaderSkeleton } from '@/components/ui/skeletons'
import { Suspense } from 'react'
import { Metadata } from 'next'
import { auth } from '@/app/auth/auth'
import { signOut } from 'next-auth/react'
import { LogoutButton } from '@/components/ui'

export const metadata: Metadata = {
	title: 'My Profile | Next.js Training',
	description: 'Generated by create next app',
}

export default async function MyProfile() {
	const session = await auth()

	//@ts-ignore
	const currentUserEmail = session!.user!.email!

	return (
		<div>
			<div className='h-[150px] relative'>
				<Suspense fallback={<ProfileHeaderSkeleton />}>
					<ProfileHeader />
				</Suspense>
			</div>
			<div className='relative w-full h-[600px] px-3 overflow-y-auto'>
				<Suspense fallback={<PostListSkeletons />}>
					<PostsList currentUserEmail={currentUserEmail} />
				</Suspense>
			</div>

			<LogoutButton className='absolute right-10 top-5 ' />
		</div>
	)
}
